services:
  - type: web
    name: auction-server
    env: node
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: auction-db
          property: connectionString
      - key: PORT
        value: 3000

databases:
  - name: auction-db
    databaseName: auction_db
    user: auction_user